version: '3.7'  
  
services:  
  redis:  
    image: redis:latest
    container_name: Redis
    restart: unless-stopped
    volumes:
      - C:/redis/:/var/lib/redis
    ports:
      - "6379:6379"
    expose:  
      - 6379