apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector: 
        "beta.kubernetes.io/os": linux
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        resources:
          limits:
            memory: 1.8Gi
            cpu: 1000m
          requests:
            memory: 1.5Gi
            cpu: 100m
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          subPath: "esdata"
          name: es-volume
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
          - name: discovery.type
            value: "single-node"
      volumes:
      - name: es-volume
        azureFile:
            secretName: azure-secret
            shareName: aksshare
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
    name: port-9200
  - port: 9300
    name: port-9300
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector: 
        "beta.kubernetes.io/os": linux
      containers:
      - name: elasticsearch
        image: docker.elastic.co/kibana/kibana:7.6.0
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
  selector:
    app: kibana