version: '3.7'

services:
  twitchsoft.telegrambot:
    image: ${DOCKER_REGISTRY-}twitchsofttelegrambot
    hostname: telegrambot
    build:
      context: .
      dockerfile: TwitchSoft.TelegramBot/Dockerfile
    restart: unless-stopped
    networks: 
      twitch-network:
        aliases:
          - telegrambot


  twitchsoft.twitchbot:
    image: ${DOCKER_REGISTRY-}twitchsofttwitchbot
    hostname: twitchbot
    build:
      context: .
      dockerfile: TwitchSoft.TwitchBot/Dockerfile
    ports:
     - "80"
    restart: unless-stopped
    networks: 
      twitch-network:
        aliases:
          - twitchbot

  twitchsoft.servicebusprocessor:
    image: ${DOCKER_REGISTRY-}twitchsoftservicebusprocessor
    hostname: servicebusprocessor
    build:
      context: .
      dockerfile: TwitchSoft.ServiceBusProcessor/Dockerfile
    restart: unless-stopped
    networks: 
      twitch-network:
        aliases:
          - servicebusprocessor

  twitchsoft.maintenance:
    image: ${DOCKER_REGISTRY-}twitchsoftmaintenance
    hostname: maintenance
    build:
      context: .
      dockerfile: TwitchSoft.Maintenance/Dockerfile
    restart: unless-stopped
    networks: 
      twitch-network:
        aliases:
          - maintenance

networks: 
  twitch-network: 
    driver: "bridge"
