version: '3.7'

services:
  twitchsoft.telegrambot:
    image: ${DOCKER_REGISTRY}twitchsofttelegrambot:latest
    build:
      context: .
      dockerfile: TwitchSoft.TelegramBot/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - ts-telegrambot


  twitchsoft.twitchbot:
    image: ${DOCKER_REGISTRY}twitchsofttwitchbot:latest
    build:
      context: .
      dockerfile: TwitchSoft.TwitchBot/Dockerfile
    ports:
     - "80"
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - ts-twitchbot

  twitchsoft.servicebusprocessor:
    image: ${DOCKER_REGISTRY}twitchsoftservicebusprocessor:latest
    build:
      context: .
      dockerfile: TwitchSoft.ServiceBusProcessor/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - ts-servicebusprocessor

  twitchsoft.maintenance:
    image: ${DOCKER_REGISTRY}twitchsoftmaintenance:latest
    build:
      context: .
      dockerfile: TwitchSoft.Maintenance/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - ts-maintenance

  twitchsoft.twitchbotorchestrator:
    image: ${DOCKER_REGISTRY}twitchsofttwitchbotorchestrator:latest
    build:
      context: .
      dockerfile: TwitchSoft.TwitchBotOrchestrator/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - ts-twitchbotorchestrator

networks: 
  twitchsoft: 
    external: true
