version: '3.7'

services:
  twitchsoft.telegrambot:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__TwitchDbContext=Server=host.docker.internal;Database=TwitchDb;User Id=sa;Password=BigPassw0rd
      - Redis__ConnectionString=host.docker.internal
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.twitchbot:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__TwitchDbContext=Server=host.docker.internal;Database=TwitchDb;User Id=sa;Password=BigPassw0rd
      - ServiceBusSettings__Host=host.docker.internal
      - Redis__ConnectionString=host.docker.internal
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.servicebusprocessor:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__TwitchDbContext=Server=host.docker.internal;Database=TwitchDb;User Id=sa;Password=BigPassw0rd
      - ServiceBusSettings__Host=host.docker.internal
      - Redis__ConnectionString=host.docker.internal
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.maintenance:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__TwitchDbContext=Server=host.docker.internal;Database=TwitchDb;User Id=sa;Password=BigPassw0rd
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
