version: '3.7'

services:
  twitchsoft.telegrambot:
    image: ${DOCKER_REGISTRY-}twitchsofttelegrambot
    build:
      context: .
      dockerfile: TwitchSoft.TelegramBot/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - telegrambot


  twitchsoft.twitchbot:
    image: ${DOCKER_REGISTRY-}twitchsofttwitchbot
    build:
      context: .
      dockerfile: TwitchSoft.TwitchBot/Dockerfile
    ports:
     - "80"
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - twitchbot

  twitchsoft.servicebusprocessor:
    image: ${DOCKER_REGISTRY-}twitchsoftservicebusprocessor
    build:
      context: .
      dockerfile: TwitchSoft.ServiceBusProcessor/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - servicebusprocessor

  twitchsoft.maintenance:
    image: ${DOCKER_REGISTRY-}twitchsoftmaintenance
    build:
      context: .
      dockerfile: TwitchSoft.Maintenance/Dockerfile
    restart: unless-stopped
    networks: 
      twitchsoft:
        aliases:
          - maintenance

networks: 
  twitchsoft: 
    external: true
