version: '3.7'

services:
  twitchsoft.telegrambot:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Redis__ConnectionString=redis
      - Elasticsearch__Url=http://elasticsearch:9200/
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.twitchbot:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Redis__ConnectionString=redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.servicebusprocessor:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Redis__ConnectionString=redis
      - Elasticsearch__Url=http://elasticsearch:9200/
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.maintenance:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  twitchsoft.twitchbotorchestrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
