version: '3.7'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        restart: unless-stopped
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - C:/elastic/data:/usr/share/elasticsearch/data
        networks:
            - twitchsoft
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        restart: unless-stopped
        ports:
            - "5601:5601"
        networks:
            - twitchsoft
        depends_on:
            - elasticsearch
volumes:
    esdata:
        driver: local
networks:
    twitchsoft:
        external: true