name: Create and Push images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-maitenance:
    name: Maintenance service build
    env: 
      DOCKER_REGISTRY: 'twitchsoft.azurecr.io'
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Azure Container Registry login
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build & Push image to ACR
    - name: Build image
      run: |
        docker build -f TwitchSoft/TwitchSoft.Maintenance/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/twitchsoftmaintenance:latest TwitchSoft
    - name: Push image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/twitchsoftmaintenance:latest
  build-servicebusprocessor:
    name: ServiceBusProcessor service build
    env: 
      DOCKER_REGISTRY: 'twitchsoft.azurecr.io'
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Azure Container Registry login
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build & Push image to ACR
    - name: Build image
      run: |
        docker build -f TwitchSoft/TwitchSoft.ServiceBusProcessor/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/twitchsoftservicebusprocessor:latest TwitchSoft
    - name: Push image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/twitchsoftservicebusprocessor:latest
  build-twitchbot:
    name: TwitchBot service build
    env: 
      DOCKER_REGISTRY: 'twitchsoft.azurecr.io'
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Azure Container Registry login
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build & Push image to ACR
    - name: Build image
      run: |
        docker build -f TwitchSoft/TwitchSoft.TwitchBot/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/twitchsofttwitchbot:latest TwitchSoft
    - name: Push image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/twitchsofttwitchbot:latest
  build-telegrambot:
    name: TelegramBot service build
    env: 
      DOCKER_REGISTRY: 'twitchsoft.azurecr.io'
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Azure Container Registry login
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build & Push image to ACR
    - name: Build image
      run: |
        docker build -f TwitchSoft/TwitchSoft.TelegramBot/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/twitchsofttelegrambot:latest TwitchSoft
    - name: Push image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/twitchsofttelegrambot:latest
  build-twitchbotorchestration:
    name: TwitchBotOrchestration service build
    env: 
      DOCKER_REGISTRY: 'twitchsoft.azurecr.io'
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Azure Container Registry login
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build & Push image to ACR
    - name: Build image
      run: |
        docker build -f TwitchSoft/TwitchSoft.TwitchBotOrchestration/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/twitchsofttwitchbotorchestration:latest TwitchSoft
    - name: Push image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/twitchsofttwitchbotorchestration:latest
        
